# Numpy 기초

> ### **Numpy**
> - **Numerical Python.** Python에서 **대규모 다차원 배열** 을 다룰 수 있게 도와주는 라이브러리
> - 데이터의 대부분은 숫자 배열로 볼 수 있다.
>   - ex) 사진 : 픽셀마다 데이터를 숫자로 표현할 수 있음
>   - ex) 소리 : 음압, 시간으로 2차원 배열이 가능하다.

## 외않 List?
- 파이썬 리스트로 계산할 수 있지만 numpy는 **빠른 연산** 을 지원하고 **메모리를 효율적으로** 사용할 수 있다.

<br><br><br><br>

## 배열 만들기

In [ ]:
list(range(10)) # [0,1,2,3,4,5,6,7,8,9]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1]:
import numpy as np
np.array([1,2,3,4,5]) # array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([[1,2],
          [3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.array([1,2,3,4],dtype='float') # 실수형태

array([1., 2., 3., 4.])

### 배열 데이터 타입 dtype
- 파이썬 List와 다르게 array는 단일타입으로 구정되있다.

- int : 정수형 (i, int_, int32, int64, i8)
- float : 실수형 (f, float_, float32 ...)
- str : 문자열 (str, U, U32)
- bool : 부울 (?, bool_)

In [ ]:
arr = np.array([1,2,3,4,5],dtype='float')
arr

array([1., 2., 3., 4., 5.])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr.astype(int) # 데이터타입 변경하기

array([1, 2, 3, 4, 5])

### 다양한 배열 만들기

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### 난수로 채워진 배열

In [ ]:
np.random.random((2,2))

array([[0.85281579, 0.40676426],
       [0.64675512, 0.74872535]])

In [ ]:
np.random.normal(0,1,(2,2)) # 정규분포로 추출. : 여기에선 평균이 0이고 표준편차가 1인 2x2 행렬

array([[0.89195082, 0.34020115],
       [0.85869581, 0.19066568]])

In [ ]:
np.random.randint(0,10,(2,2))

array([[0, 4],
       [5, 7]])

In [3]:
#0부터 5사이 랜덤한 값(정수)이 담긴 3x5 array를 만들어 봅시다!

array = np.random.randint(0,5,size=(3,5))
array

array([[1, 1, 4, 1, 0],
       [2, 1, 1, 4, 1],
       [3, 3, 2, 2, 0]])

## 배열 기초

In [5]:
x2 = np.random.randint(10, size=(3, 4)) # 3 x 4 배열 생성
x2

array([[0, 5, 0, 1],
       [7, 4, 2, 1],
       [6, 2, 9, 3]])

In [6]:
x2.ndim # n차원 배열

2

In [7]:
x2.shape # 배열의 형태 (n * m)

(3, 4)

In [8]:
x2.size # 원소의 개수

12

In [10]:
x2.dtype # 데이터타입

dtype('int64')

## 데이터 찾고 잘라내기
- indexing : 인덱스로 값을 찾기

In [11]:
x = np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
x[3]

3

In [13]:
x[7] # 에러발생

IndexError: ignored

In [14]:
x[0] = 10
x

array([10,  1,  2,  3,  4,  5,  6])

- slicing : 인덱스 값으로 배열의 부분을 가져오기

In [15]:
x = np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
x[1:]

array([1, 2, 3, 4, 5, 6])

In [17]:
x[:4]

array([0, 1, 2, 3])

In [18]:
x[::2]

array([0, 2, 4, 6])