## 모양 바꾸기
- reshape : array의 shape를 변경한다


In [3]:
import numpy as np

In [4]:

x = np.arange(8)
x.shape # (8,). 1차원 8개를 가진 배열

(8,)

In [6]:
x2 = x.reshape((2,4)) # 2X4 로 reshape
x2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
x2.shape

(2, 4)

## 이어 붙이고 나누기
- concatenate : array를 이어 붙인다.

In [11]:
x = np.array([0,1,2])
y = np.array([3,4,5])
np.concatenate([x,y])

array([0, 1, 2, 3, 4, 5])

- np.concatenate: axis 축을 기준으로 이어 붙일 수 있다

In [12]:
matrix = np.arange(4).reshape(2,2)
matrix

array([[0, 1],
       [2, 3]])

In [14]:
np.concatenate([matrix, matrix], axis=0) # 아래방향

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [15]:
np.concatenate([matrix, matrix], axis=1) # 가로방향

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

np.slit : axis 축을 기준으로 나누

In [17]:
matrix = np.arange(16).reshape(4,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
upper, lower = np.split(matrix, [3], axis=0)

In [19]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
lower

array([[12, 13, 14, 15]])

In [21]:
upper, lower = np.split(matrix, [3], axis=1)

In [22]:
upper

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [23]:
lower

array([[ 3],
       [ 7],
       [11],
       [15]])