# Numpy 연산
- 파이썬에서 루프 연산은 느리다.
- 간단한 부분은 상관없는데, 규모가 큰 계산을 하게 된다면 시간의 차이는 크게 된다.

## 기본 연산
- array는 +, -, *, / 에 대한 기본 연산을 지원한다.

In [4]:
import numpy as np

In [5]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [6]:
x + 5

array([5, 6, 7, 8])

In [7]:
x - 5

array([-5, -4, -3, -2])

In [8]:
x * 5

array([ 0,  5, 10, 15])

In [9]:
x / 5

array([0. , 0.2, 0.4, 0.6])

## 행렬간 연산
- 다차원 행렬에도 적용 가능

In [10]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [12]:
y = np.random.randint(10, size = (2,2))
y

array([[5, 0],
       [3, 5]])

In [13]:
x + y

array([[5, 1],
       [5, 8]])

In [14]:
x - y

array([[-5,  1],
       [-1, -2]])