# 브로드 캐스팅
- Broadcasting : shape이 다른 array끼리 연산


In [1]:
import numpy as np

In [2]:
matrix = np.array([[2,4,2],[6,5,9],[9,4,7]])
matrix

array([[2, 4, 2],
       [6, 5, 9],
       [9, 4, 7]])

In [3]:
matrix + 5

array([[ 7,  9,  7],
       [11, 10, 14],
       [14,  9, 12]])

In [4]:
matrix + np.array([1,2,3])
# [[1,2,3], [1,2,3], [1,2,3]]을 더한 것과 같다

array([[ 3,  6,  5],
       [ 7,  7, 12],
       [10,  6, 10]])

In [6]:
x = np.arange(3)
x

array([0, 1, 2])

In [8]:
y = x.reshape((3,1))
y

array([[0],
       [1],
       [2]])

In [9]:
y + x # [[0],[1],[2]] + [0,1,2]
# [[0,0,0],[1,1,1],[2,2,2]] + [[0,1,2],[0,1,2],[0,1,2]]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])