# 집계함수
- 집계 : 데이터에 대한 요약 통계를 볼 수 있다

In [3]:
import numpy as np

In [4]:
x = np.arange(8).reshape((2,4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
np.sum(x) # 원소의 합

28

In [6]:
np.min(x) # 원소 최솟값

0

In [7]:
np.max(x) # 원소 최댓값

7

In [8]:
np.mean(x) # 원소 평균값

3.5

In [9]:
np.std(x) # 표준편차

2.29128784747792

In [10]:
np.sum(x, axis=0) # 열의 합

array([ 4,  6,  8, 10])

In [11]:
np.sum(x, axis=1) # 행의 합

array([ 6, 22])

## 마스킹 연산
- True, False array를 통해 특정 값들을 뽑아내는 방

In [13]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [14]:
x < 3

array([ True,  True,  True, False, False])

In [15]:
x > 5

array([False, False, False, False, False])

In [16]:
x[x < 3]

array([0, 1, 2])

In [17]:
x[x> 5]

array([], dtype=int64)